### ISSUE TITLE
Use Gecko api for coin price

### ISSUE THREAD

**Issue by Anmol1696** [persistenceOne/persistenceWallet#236]
## Improvement

Proxy is used to fetch coin price, instead we should use coin gecko for global average.

## Motivation

It looks like proxy app seems to be a hacky solution, where as gecko will be more proper

## Pitch

Use Gecko packages to fetch coin price from gecko instead

**Comment by puneet2019** [comment]
makes sense, when the app was launched there was only the listing exchange api to help with coin price, we can switch to coin gecko now.

**Comment by puneet2019** [comment]
#266 closes this
