### ISSUE TITLE
explorer.persistence.one doesn't work with uBlock Origin enabled

### ISSUE THREAD

**Issue by Freak12Techno** [persistenceOne/persistenceWallet#240]
I have uBlock origin enabled on my Firefox and this prevents the website from working completely: apparently because the request for the file `https://explorer.persistence.one/javascriptRoutes` is blocked by uBlock. After that I see the following in the browser devtools:

```
Uncaught ReferenceError: jsRoutes is not defined
```

and the website becomes pretty unresponsive:
![image](https://user-images.githubusercontent.com/83376337/121675367-fa2ed380-cabb-11eb-8688-4e1b5280bfc3.png)

Disabling uBlock Origin for this website, as well as using another browser (Brave in my case) makes it work

I'm using uBlock Origin v1.35.2, can provide more details if needed.

**Comment by avkr003** [comment]
Hi!

Looks you have disabled all the javascript from the website using uBlock. To enable it please uncheck the circled in uBlock settings.

<img width="1440" alt="Screenshot 2021-06-11 at 4 29 04 PM" src="https://user-images.githubusercontent.com/57705190/121676641-7a603380-cad2-11eb-92ff-7ef5e574f574.png">

**Comment by Freak12Techno** [comment]
I have it unchecked though
<img width="1440" alt="Screenshot 2021-06-11 at 15 14 46" src="https://user-images.githubusercontent.com/83376337/121684783-db363e80-cac7-11eb-8793-0540ecb3f2a0.png">

**Comment by avkr003** [comment]
HI,

I failed to replicate this issue in firefox with the configuration you have shown. The load time of the website was high due to some other issue that has been resolved. Can you confirm if this issue still persists?

**Comment by Freak12Techno** [comment]
![image](https://user-images.githubusercontent.com/83376337/123924451-a7498d00-d992-11eb-88e9-899425364f0c.png)
Still doesn't work with uBlock enabled. Works when I disable it though.

Some additional info:
Firefox 89.0.1 (64-bit)
uBlock Origin v1.36.0

**Comment by Freak12Techno** [comment]
![image](https://user-images.githubusercontent.com/83376337/123925570-b7ae3780-d993-11eb-8dac-e90a3418d64b.png)
Apparently there's something in RUS: RU AdList which is blocking it, that's why you cannot reproduce it

**Comment by puneet2019** [comment]
@Freak12Techno, it seems you figured it out, should I close the issue?

**Comment by Freak12Techno** [comment]
I think so. Maybe add a notice to the explorer page or some kind of fallback if the script won't be able to load? (suggesting to disable ad blocking software)
Not sure if there's something more than that that could be done.
