### ISSUE TITLE
Unable to delegate to inactive validator 

### ISSUE THREAD

**Issue by Andrew-Pohl** [persistenceOne/persistenceWallet#261]
No option to delegate to inactive validators via the persistence wallet. It gives the option to only redelegate and then because you haven't delegated to it before the drop down on the next page is blank. It looks to be the same for all inactive validators. 

![image](https://user-images.githubusercontent.com/55916961/125864823-77a24052-ab46-45c7-b669-460856849350.png)

**Comment by puneet2019** [comment]
@Andrew-Pohl will be taking this up in next release.

**Comment by puneet2019** [comment]
#266 closes this
