### ISSUE TITLE
Performing a send transaction by transferring the whole Amount, however certain numbers remain in decimal digits

### ISSUE THREAD

**Issue by PradeepaTrackdfect** [persistenceOne/persistenceWallet#293]
@puneet2019 

**Steps to Reproduce :**

1. Launch URL
2. Click on Sign-in button
3. Click on Continue with Address
4. Enter Valid Address and click on submit
5. Click on Sent Section
6. Enter valid recipient Address, enter the entire amount which is transferable (excluding the fee), and complete the transaction.
7. Check the Transferable balance

**Actual Result:** It displays some decimal values after sending the entire amount
**Expected Result:** It should be zero

**Issue Attachment:**
https://drive.google.com/file/d/1U70EsIiDKyt9EGUHwviJCLDREcHEj2HJ/view?usp=drivesdk

**Comment by blackpanther1881** [comment]
@PradeepaTrackdfect fixed

**Comment by PradeepaTrackdfect** [comment]
@blackpanther1881 
The issue still exists.
Cant able to send the entire amount which is transferable (excluding the fee)

Attach video for reference:
https://drive.google.com/file/d/1f3QRO7qfIMPGYJukK6ga3S_JyN9BfoWE/view?usp=drivesdk

**Comment by blackpanther1881** [comment]
@PradeepaTrackdfect can you check now. fixed in new version

**Comment by PradeepaTrackdfect** [comment]
@blackpanther1881 
working as expected. Closing this issue 

Attached video for reference:
https://drive.google.com/file/d/1P4JXFVavHP0WKjIyhDCJyHKBiKQ38H9J/view?usp=drivesdk
