### ISSUE TITLE
In Staking page, sorting is not working under all Validators/Delegated section

### ISSUE THREAD

**Issue by PradeepaTrackdfect** [persistenceOne/persistenceWallet#296]
@puneet2019 

Repro Steps:
1. Launch URL
2. Click on Signin button
3. Click on Continue with Address
4. Enter Valid Address and click on submit
5. In the menubar, select Staking.
6. Click on Validators under the All Validators /Delegated section 

Actual Result: Its not sort the validators list
Expected Result: It should sort based on alphabetical order by ascending/descending order

Bug Attachment Link:
https://drive.google.com/file/d/1fYFREGpN3HTh-mN9QUr5hPgdGtl_NMGm/view?usp=drivesdk

**Comment by PradeepaTrackdfect** [comment]
Reopening this issue @puneet2019

**Comment by blackpanther1881** [comment]
@PradeepaTrackdfect fixed

**Comment by PradeepaTrackdfect** [comment]
Tested. Working as expected. Closing this issue
@blackpanther1881
