### ISSUE TITLE
Facing issue in the Amount Field of all Transactions, while scrolling up/down. When you click on Transferable balance, the next button is greyed out, hence that won't be able to complete the transaction.

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#300]
@puneet2019 

Steps to Reproduce :
1.Log into the application
2.Enter Recipient Address(send transaction)
3.Click on 'Transferable Balance'
4.Scrol up/down in 'Amount' filed
5.Again click on 'Transferable Balance'

Notice the issue, Next button still gets deactivated
(happening for all transactions)

Expected Result: Next button should get activated
Actual Result: Next button gets deactivated

Attachment: https://drive.google.com/file/d/10S1jfymYzaoVe6CkUejysjN0GgzfF7cj/view?usp=sharing

**Comment by blackpanther1881** [comment]
You are scrolling upon on input field.  We can change value of the input field (type number) on scroll and using arrows.  So bcz of scrolling on input field the value increasing and giving error.

**Comment by Manojkumar4444** [comment]
Yes, the value is increasing as I scroll up, After that I'm clicking on the Transferable Balance.  As a result, the error message remains visible and the Next button remains inactive. So unable to complete that transaction even with the transferable amount.

**Comment by Manojkumar4444** [comment]
@puneet2019 Resolved
