### ISSUE TITLE
After withdrawing the Rewards to another account, Rewards are not credited to the revised account and are not subtracted from the main account

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#306]
@puneet2019 

Steps to Reproduce:
1.Log in to the application
2.Click on claim rewards
3.click on Set up address
4.Enter Revised Address
5.Click on next
6.Choose Key Store file and enter password
7.Click on Submit

Notice the issue, Rewards are not credited to the revised account and not deducting from the main account

Expected Results : Rewards should get credit to the revised account and should get deduct from the main account
Actual Result: Rewards are not credited to the revised account and not deducting from the main account

Attachment: https://drive.google.com/file/d/1fX2ab_BAQOQMhJmeKjXGOUdnDP9UQYNZ/view?usp=sharing

**Comment by blackpanther1881** [comment]
set rewards withdraw address is separate transaction. after adding revised address try claiming rewards.

**Comment by Manojkumar4444** [comment]
Retested and working fine
