### ISSUE TITLE
Showing an error message that the Gas fee is insufficient to proceed with Redelegate transaction, yet it is detecting the Gas fee from the Total balance.

### ISSUE THREAD

**Issue by PradeepaTrackdfect** [persistenceOne/persistenceWallet#312]
@puneet2019 

**Repro Steps:**
1.Launch URL
2.Click on Sign inbutton
3.Click on Continue with Address 
4. Enter Valid Address (persistence16wn9cs22598vp59fptyfzc8ujcmwhvs3kj0pel) and Click on Submit
5. Note down the Total balance from bal section
5. Click on Staking from the menu bar
6. Click on Delegated tab
7. Click on Action button next to DSRV
8. Select Redelegate and perform redelgate transaction, It display the error message
9. Now check the Total  balance from balance section

**Actual Result:** It detects the gas fee for the unsuccessful transaction
**Expected Result:** It should not detect the gas fee for an unsuccessful transaction

**Attachment  :**  
https://drive.google.com/file/d/16ds3WoQRn9o2YgASL5ug1ZAlkDNQtbfr/view?usp=drivesdk

**Comment by puneet2019** [comment]
fee is deducted for invalid transactions also, it's because validator spent efforts in validating the transaction.

**Comment by PradeepaTrackdfect** [comment]
Okay, thanks for the clarification. Closing this issue @puneet2019
