### ISSUE TITLE
For the word "users", the apostrophe(') sign is not properly positioned

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#323]
@puneet2019 

Bug category: UI
Priority : Low

Steps to Reproduce:
1.Launch URL
2.Click on Create wallet

Expected Result:  apostrophe(') sign should get arrange correctly
Actual Results: apostrophe(') sign is not properly positioned

Attachment: https://drive.google.com/file/d/1zMOwVlVR1H6Gu_GEVWnERzOuthVFm3th/view?usp=sharing

**Comment by puneet2019** [comment]
![image](https://user-images.githubusercontent.com/59960662/142622109-f9fe868b-0b85-41d8-a058-3f75e1536616.png)

**Comment by Manojkumar4444** [comment]
Invalid issue & closing
