### ISSUE TITLE
Unable to go on after inputting the maximum value(4294967295) in the Account number/index fields

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#326]
@puneet2019 

Steps to Reproduce:
1.Launch URL
2.Create wallet
3.Enter Mnemonic
4.Expand Advanced tab
5.Enter max value in Account number/index fields (4294967295)
6.Click on Next button
Notice the issue, Unable to navigate to next model

Expected Results: Should be able to navigate to next model
Actual Result: Unable to navigate to next model

Attachment: https://drive.google.com/file/d/1IGKaKdzh4-N39N2fUvx_OvtmCYlwHyCQ/view?usp=sharing

**Comment by puneet2019** [comment]
<= 2147483647 
 need to fix regex to

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed. max number is 2147483647

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 Resolved
