### ISSUE TITLE
The previous validation message is still visible on the model after returning back

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#330]
@puneet2019 

Steps to Reproduce:
1.Launch URL
2.Click on Generate KeyStore File
3.Click on Change KeyStore password
4.Choose KeyStore file & enter password
5.Enter password with spaces/less than 3 characters
6.Click on back button

Notice the issue, previous validation message is still visible on the model

Expected Results: previous validation message should get appear on previous model
Actual Result: previous validation message is still visible on the model

Attachment: https://drive.google.com/file/d/1ZEluqVNdTaxuolQn-TvwiqRXts0BQvCm/view?usp=sharing

**Comment by ZaidKhan144** [comment]
@Manojkumar4444 Hey, could you assign me, please? I would like to do this.

**Comment by Manojkumar4444** [comment]
@puneet2019 Resolved
