### ISSUE TITLE
"Invalid Recipient Address" Error message is not aligned correctly when initiating a transaction with invalid address

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#339]
@puneet2019 

Steps to Reproduce:
1.Launch URL
2.Sign in
3.Enter invalid Recipient Address
4.Click on Next

Notice the issue, Error message is not aligned correctly

Expected Result: Error messages should get align correctly
Actual Result: Error message is not aligned correctly

Attachment: https://drive.google.com/file/d/1KAp0ioRyKaA9f7Pwf4FlQrZxb3u8JFcN/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 Resolved
