### ISSUE TITLE
After click on change KeyStore file, previous error message still showing on model

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#340]
@puneet2019 

Steps to Reproduce:
1.Launch the URL
2.Sign in
3.Make send transaction
4.Enter invalid account details
5.Click on change KeyStore file

Notice the issue,  previous error message still showing on model

Expected Result:  Previous error message should not get appear on another model
Actual Result:  Previous error message still showing on model

Attachment: https://drive.google.com/file/d/1_hiTnryPGx2FbNz1gqXYsjwXO1IsFpHh/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 Resolved
