### ISSUE TITLE
While making a transaction after importing the Wallet using the KeyStore file and providing an Account Number/Index. Noticing the problem and receiving a validation message

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#341]
@puneet2019 

Steps to Reproduce:
1.Launch URL
2.Click on Create Wallet
3.Click on Import wallet
4.Choose KeyStore file & Enter password
5.Click on Next
6.Enter Account Number & Index
7.Login to the application
8.Generate new KeyStore file
9.Make any transaction

Notice the issue, receiving a validation message

Expected Result: Should be able to make transaction successfully
Actual Result: Noticing the problem and receiving a validation message

Attachment: https://drive.google.com/file/d/1eZRuOi5OhV2NIaqRURo4Jhcvvq_5qNP6/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 Resolved
