### ISSUE TITLE
After entering invalid Mnemonic then again enter correct Mnemonic and click on back. Notice the issue, "Invalid Mnemonic" message still showing

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#343]
@puneet2019 

Steps to Reproduce:
1.Launch the URL
2.Click on Create Wallet button
3.Click on NEXT button on "About Persistence Wallet" model
4.Click on Next on "Mnemonic" model
5.Fill wrong Mnemonic
6.Click on Submit
7.Click on Back
8.Enter valid Mnemonic & Submit
9.Click on Back

Expected Result: Previous page error message should not get appear
Actual Result: "Invalid Mnemonic" message still showing

Attachment: https://drive.google.com/file/d/1td684rJto2bZ3DpJD15vXgBkRYsgBFyA/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 Resolved
