### ISSUE TITLE
Getting an "Invalid Recipient Address" message without entering any address

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#351]
@puneet2019 

Steps to Reproduce:
1.Launch URL
2.Sign In
3.Click on Recipient Address

Notice the issue, getting validation message

Expected Result: Without entering anything, should not get any validation message
Actual Result: Getting an "Invalid Recipient Address" message without entering any address

Attachment: https://drive.google.com/file/d/1q77XDxG6iPv2K9m6T0jTEqdd6aIbd1UL/view?usp=sharing

**Comment by blackpanther1881** [comment]
we added validations like that. onClick ouside we added validating field

**Comment by Manojkumar4444** [comment]
@blackpanther1881 got it. thanks
