### ISSUE TITLE
The "KeyStore Password Reset" model does not auto-refresh after closing and reopening

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#352]
@puneet2019 

Steps to Reproduce:
1.Launch URL
2.Click on Generate KeyStore
3.Click on Change KeyStore Password
4.Choose file & enter password
5.Close the model
6.Again open

Notice the issue, Entered details still showing

Expected Result: After reopen the model, details should get auto refresh
Actual Result: The "KeyStore Password Reset" model does not auto-refresh after closing and reopening

Attachment: https://drive.google.com/file/d/1PZW-fTRfsAd6kpj7DrtSj8xzdgTa9otd/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 Resolved
