### ISSUE TITLE
Unable to close "KeyStore Password Reset" model

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#353]
@puneet2019 

Steps to Reproduce:
1.Launch URL
2.Click on Generate KeyStore
3.Click on Change KeyStore Password
4.Choose file & enter password
5.Enter new password
6.Click on Close

Notice the issue, Unable to close the model

Expected Result: User should be able to close the models
Actual Result: Unable to close "KeyStore Password Reset" model

Attachment: https://drive.google.com/file/d/1OMn_FxIq0UWzPxWbb1AqbYqVNCAOqnn5/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 Resolved
