### ISSUE TITLE
Entered Amount remains in fields on Delegation/Redelegation/Unbond Amount models after close and reopening the models

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#354]
@puneet2019 

Steps to Reproduce:
1.Launch URL
2.Sign in
3.Click on Staking
4.Click on any Validator
5.Click on Delegation/Redelegation/Unbond Amount
6.Enter Amount
7,Close & open same

Notice the issue, Entered Amount remains in fields

Expected Result: Fields should get Auto refresh
Actual Result: Entered Amount remains in fields

Attachment: https://drive.google.com/file/d/1avHsrKNJc0fUhaynC-A9N5at68LW1PEE/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 Resolved
