### ISSUE TITLE
User able to open 'Generate KeyStore file' model by clicking away to the link

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#361]
@puneet2019 

Steps to Reproduce:
1.Launch URL
2.Click away to 'Generate keystore file' link

Notice the issue, able to open the model

Expected Result: Should not be able to open by click away to the link
Actual Result: Able to open by clicking away

Attachment: https://drive.google.com/file/d/1LwFfdRAWkiJYmbmULhLtjFf3EceF0haI/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 Resolved
