### ISSUE TITLE
On change Keystore password page, getting incorrect validation message

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#366]
@puneet2019 

1.Launch URL
2.Click on Generate Keystore file
3.Click on Change Keystore file password
4.Choose file & password then Submit
5.CLick on Back button
6.Click on Submit without file & password

Notice the issue, getting "Incorrect password" error message

Expected Result: Should get proper validation message
Actual Result: getting "Incorrect password" error message

Attachment: https://drive.google.com/file/d/1r2IGSg_8OtwZQXhUYqz0KAHzQQvAcf9k/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444  fixed
