### ISSUE TITLE
After close and reopen the Generate Keystore file model, Previous error message still showing

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#368]
@puneet2019 

Steps to Reproduce:

1.Launch URL
2.Click on Generate Keystore file
3.Enter invalid Mnemonic 
4.Close the model
5.Again open

Notice the issue, still "Invalid mnemonic" error message showing

Expected Result: Model should get refresh
Actual Result: Previous error message still showing

Attachment: https://drive.google.com/file/d/1HCYkk2OS8cyphQ6InWDC4zaSkg2zxMVW/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 Resolved
