### ISSUE TITLE
After close and reopen the KeyStore Password Reset model, Previous error message still showing

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#369]
@puneet2019 

Steps to Reproduce:

1.Launch URL
2.Click on Generate Keystore file
3.Click on Change Keystore password
4.Choose file and enter Invalid password
5.Click on submit
6.Close & open the same

Notice the issue, still "Incorrect password" error message showing on model

Expected Result: Model should get refresh
Actual Result: Previous error message still showing

Attachment: https://drive.google.com/file/d/1WOBCxLt3IqdlnIOys1VfppiUAWEh3r7Y/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 Resolved
