### ISSUE TITLE
Text is not aligned correctly on Sign in through Kepler model

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#370]
@puneet2019 

Steps to Reproduce:

1.Launch URL
2.Click on Sign in
3.Choose Kepler
4.Cancel transaction on Kepler end

Notice the issue, Text is not aligned correcly

Expected Result: Text should get align correctly
Actual Result: Text is not aligned correctly on Sign in through Kepler model

Attachment: https://drive.google.com/file/d/1o4foQ6Q-zMrTeRWFPZxpmivy2uZqfk1r/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 Resolved
