### ISSUE TITLE
While Signing through Invalid Address, close/back and reopen. Notice the issue, Previous error message still showing

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#372]
@puneet2019 

1.Launch URL
2.Click on Sign in
3.Choose Address
4.Enter invalid Address
5.Click on Back/Close
6.Again open

Notice the issue, Previous error message still showing

Expected Result: Model should get refresh
Actual Result: Previous error message still showing

Attachment: https://drive.google.com/file/d/1aRkCtGjyFXhBmBAIeYFFW2dM2tozEe55/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881  Resolved
