### ISSUE TITLE
While Signing through Keystore file, enter wrong password and close/back and reopen. Notice the issue, Previous error message still showing

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#373]
@puneet2019 

1.Launch URL
2.Click on Sign in
3.Choose Address
4.Enter invalid Address
5.Click on Back/Close
6.Again open

Notice the issue, Previous error message still showing

Expected Result: Model should get refresh
Actual Result: Previous error message still showing

Attachment: https://drive.google.com/file/d/1-satfAmnl56v4GftbhwgeFbr-iQeojdo/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 fixed
