### ISSUE TITLE
While making a transaction with Different Keystore file, getting two different validation messages depending on correct/wrong passwords to that particular file

### ISSUE THREAD

**Issue by Manojkumar4444** [persistenceOne/persistenceWallet#375]
@puneet2019 

1.Launch URL
2.Click on Sign in
3.Enter Address, Amount and send
4.Choose Keystore file which is not belongs to the Signed in account
5.Enter correct/incorrect password to that particular file

Notice the issue, getting two different validation messages depending on correct/wrong passwords to that particular file

Expected Result: Should get proper validation message
Actual Result: getting two different validation messages depending on correct/wrong passwords to that particular file

Attachment: https://drive.google.com/file/d/1MfT0PoE3WgYkqfMse5vjLxcqnVnN4A0H/view?usp=sharing

**Comment by blackpanther1881** [comment]
@Manojkumar4444 intentionally added new different error messages.
1. first we are checking keystore file password correct or not.
2. if it is correct then proceeding with txn there we are checking address matching with login address or not.

**Comment by Manojkumar4444** [comment]
@puneet2019 @blackpanther1881 oh got and closing the issue
